# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: v0.14.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_machine_finalize_allocation_request import V1MachineFinalizeAllocationRequest  # noqa: E501
from metal_python.rest import ApiException


class TestV1MachineFinalizeAllocationRequest(unittest.TestCase):
    """V1MachineFinalizeAllocationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MachineFinalizeAllocationRequest(self):
        """Test V1MachineFinalizeAllocationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_machine_finalize_allocation_request.V1MachineFinalizeAllocationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
