# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: v0.37.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.metal_ntp_server import MetalNTPServer  # noqa: E501
from metal_python.rest import ApiException


class TestMetalNTPServer(unittest.TestCase):
    """MetalNTPServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetalNTPServer(self):
        """Test MetalNTPServer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.metal_ntp_server.MetalNTPServer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
