# coding: utf-8

"""
    metal-api

    Resource for managing pure metal  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_size_constraint import V1SizeConstraint  # noqa: E501
from metal_python.rest import ApiException


class TestV1SizeConstraint(unittest.TestCase):
    """V1SizeConstraint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1SizeConstraint(self):
        """Test V1SizeConstraint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_size_constraint.V1SizeConstraint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
