# coding: utf-8

"""
    metal-api

    Resource for managing pure metal  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.wrappers_int32_value import WrappersInt32Value  # noqa: E501
from metal_python.rest import ApiException


class TestWrappersInt32Value(unittest.TestCase):
    """WrappersInt32Value unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWrappersInt32Value(self):
        """Test WrappersInt32Value"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.wrappers_int32_value.WrappersInt32Value()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
