# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: v0.22.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.httperrors_http_error_response import HttperrorsHTTPErrorResponse  # noqa: E501
from metal_python.rest import ApiException


class TestHttperrorsHTTPErrorResponse(unittest.TestCase):
    """HttperrorsHTTPErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttperrorsHTTPErrorResponse(self):
        """Test HttperrorsHTTPErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.httperrors_http_error_response.HttperrorsHTTPErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
