# coding: utf-8

"""
    metal-api

    Resource for managing pure metal  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_machine_abort_reinstall_request import V1MachineAbortReinstallRequest  # noqa: E501
from metal_python.rest import ApiException


class TestV1MachineAbortReinstallRequest(unittest.TestCase):
    """V1MachineAbortReinstallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MachineAbortReinstallRequest(self):
        """Test V1MachineAbortReinstallRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_machine_abort_reinstall_request.V1MachineAbortReinstallRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
