# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: v0.22.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_power_metric import V1PowerMetric  # noqa: E501
from metal_python.rest import ApiException


class TestV1PowerMetric(unittest.TestCase):
    """V1PowerMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PowerMetric(self):
        """Test V1PowerMetric"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_power_metric.V1PowerMetric()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
