# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: v0.22.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_machine_console_password_response import V1MachineConsolePasswordResponse  # noqa: E501
from metal_python.rest import ApiException


class TestV1MachineConsolePasswordResponse(unittest.TestCase):
    """V1MachineConsolePasswordResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MachineConsolePasswordResponse(self):
        """Test V1MachineConsolePasswordResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_machine_console_password_response.V1MachineConsolePasswordResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
