# coding: utf-8

"""
    metal-api

    Resource for managing pure metal  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_partition_update_request import V1PartitionUpdateRequest  # noqa: E501
from metal_python.rest import ApiException


class TestV1PartitionUpdateRequest(unittest.TestCase):
    """V1PartitionUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PartitionUpdateRequest(self):
        """Test V1PartitionUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_partition_update_request.V1PartitionUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
