# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: v0.40.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_network_consumption import V1NetworkConsumption  # noqa: E501
from metal_python.rest import ApiException


class TestV1NetworkConsumption(unittest.TestCase):
    """V1NetworkConsumption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1NetworkConsumption(self):
        """Test V1NetworkConsumption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_network_consumption.V1NetworkConsumption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
