# coding: utf-8

"""
    metal-api

    Resource for managing pure metal  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.metal_switch_sync import MetalSwitchSync  # noqa: E501
from metal_python.rest import ApiException


class TestMetalSwitchSync(unittest.TestCase):
    """MetalSwitchSync unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetalSwitchSync(self):
        """Test MetalSwitchSync"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.metal_switch_sync.MetalSwitchSync()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
