# coding: utf-8

"""
    metal-api

    Resource for managing pure metal  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import metal_python
from metal_python.models.v1_machine_allocation import V1MachineAllocation  # noqa: E501
from metal_python.rest import ApiException


class TestV1MachineAllocation(unittest.TestCase):
    """V1MachineAllocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MachineAllocation(self):
        """Test V1MachineAllocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metal_python.models.v1_machine_allocation.V1MachineAllocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
