# coding: utf-8

"""
    metal-api

    API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1MachineIpmiReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'leases': 'dict(str, str)',
        'partitionid': 'str'
    }

    attribute_map = {
        'leases': 'leases',
        'partitionid': 'partitionid'
    }

    def __init__(self, leases=None, partitionid=None):  # noqa: E501
        """V1MachineIpmiReport - a model defined in Swagger"""  # noqa: E501

        self._leases = None
        self._partitionid = None
        self.discriminator = None

        self.leases = leases
        self.partitionid = partitionid

    @property
    def leases(self):
        """Gets the leases of this V1MachineIpmiReport.  # noqa: E501

        the active leases to be reported by a management server  # noqa: E501

        :return: The leases of this V1MachineIpmiReport.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._leases

    @leases.setter
    def leases(self, leases):
        """Sets the leases of this V1MachineIpmiReport.

        the active leases to be reported by a management server  # noqa: E501

        :param leases: The leases of this V1MachineIpmiReport.  # noqa: E501
        :type: dict(str, str)
        """
        if leases is None:
            raise ValueError("Invalid value for `leases`, must not be `None`")  # noqa: E501

        self._leases = leases

    @property
    def partitionid(self):
        """Gets the partitionid of this V1MachineIpmiReport.  # noqa: E501

        the partition id for the ipmi report  # noqa: E501

        :return: The partitionid of this V1MachineIpmiReport.  # noqa: E501
        :rtype: str
        """
        return self._partitionid

    @partitionid.setter
    def partitionid(self, partitionid):
        """Sets the partitionid of this V1MachineIpmiReport.

        the partition id for the ipmi report  # noqa: E501

        :param partitionid: The partitionid of this V1MachineIpmiReport.  # noqa: E501
        :type: str
        """
        if partitionid is None:
            raise ValueError("Invalid value for `partitionid`, must not be `None`")  # noqa: E501

        self._partitionid = partitionid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1MachineIpmiReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1MachineIpmiReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
