name: Auto Generate

on:
  push:
    branches:
      - auto-generate/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Generate
      run: |
        if ! which yq; then
          sudo curl -Lo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/4.9.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        fi
        make generate-client
    - name: Push
      run: |
        if ! git diff --exit-code; then
          git config --global user.name "auto-build"
          git config --global user.email "info@metal-stack.io"
          git add .
          git commit -m "Bump to version $(python3 -c 'from version import VERSION; print(VERSION)')"
          git push
        fi
